In [1]:
from numpy import *
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
from pprint import pprint

Ejercicio 7.10.5. Diseñe una función media(a, axis) que haga lo mismo que la función mean
utilizando la definición de media: a_m = suma(a[j]) / n

Haga que axis tenga un valor por defecto None y tenga presente que también puede tomar valores
positivos y negativos. Compare ambas funciones para comprobar que dan los mismos resultados con
arrays de prueba de varias dimensiones.

In [2]:
a = random.randint(0, 100, size=(3, 4, 2))

pprint(a.shape)
s = sum(a, axis=0)
pprint(s)
pprint(s.shape)
n = prod(a.shape) / prod(s.shape)
pprint(n)
pprint(mean(a, axis=0))
pprint(sum(a, axis=0) / n)


(3, 4, 2)
array([[ 72, 163],
       [157, 107],
       [126, 128],
       [183, 209]])
(4, 2)
3.0
array([[24.        , 54.33333333],
       [52.33333333, 35.66666667],
       [42.        , 42.66666667],
       [61.        , 69.66666667]])
array([[24.        , 54.33333333],
       [52.33333333, 35.66666667],
       [42.        , 42.66666667],
       [61.        , 69.66666667]])


In [3]:
def media(a, axis=None):
    s = sum(a, axis=axis)
    n = prod(a.shape) / prod(s.shape)
    return s / n


In [4]:
a = random.randint(0, 100, size=(3, 4, 2))
pprint(media(a,0))
pprint(a.shape)
pprint(a)


array([[44.66666667, 18.33333333],
       [67.33333333, 51.33333333],
       [65.33333333, 52.        ],
       [47.66666667, 54.        ]])
(3, 4, 2)
array([[[81,  5],
        [67, 78],
        [78, 30],
        [94, 94]],

       [[ 2, 43],
        [78, 55],
        [37, 92],
        [47, 16]],

       [[51,  7],
        [57, 21],
        [81, 34],
        [ 2, 52]]])


In [5]:

mean(a, axis=-2)

array([[80.  , 51.75],
       [41.  , 51.5 ],
       [47.75, 28.5 ]])

In [6]:
pprint(a[0])

array([[81,  5],
       [67, 78],
       [78, 30],
       [94, 94]])


In [7]:
pprint(a.shape)
prod(a.shape)

(3, 4, 2)


24

In [8]:
pprint(sum(a, axis=0).shape)
prod(sum(a, axis=0).shape)

(4, 2)


8

In [9]:
sum(a, axis=0) / ( prod(a.shape) / prod(sum(a, axis=0).shape) )

array([[44.66666667, 18.33333333],
       [67.33333333, 51.33333333],
       [65.33333333, 52.        ],
       [47.66666667, 54.        ]])

In [10]:
mean(a, axis=0)

array([[44.66666667, 18.33333333],
       [67.33333333, 51.33333333],
       [65.33333333, 52.        ],
       [47.66666667, 54.        ]])

In [11]:
axis = None
pprint(sum(a, axis=axis).shape)
pprint(int(prod(sum(a, axis=axis).shape)))
pprint(int(prod(a.shape)/prod(sum(a, axis=axis).shape)))
pprint(int(prod(a.shape)))

()
1
24
24


In [12]:
axis = 0
pprint(sum(a, axis=axis).shape)
pprint(int(prod(sum(a, axis=axis).shape)))
pprint(int(prod(a.shape)/prod(sum(a, axis=axis).shape)))
pprint(int(prod(a.shape)))

(4, 2)
8
3
24


In [13]:
axis = (0,1)
pprint(sum(a, axis=axis).shape)
pprint(int(prod(sum(a, axis=axis).shape)))
pprint(int(prod(a.shape)/prod(sum(a, axis=axis).shape)))
pprint(int(prod(a.shape)))

(2,)
2
12
24


In [14]:
pprint(a.shape)
pprint(sum(a, axis=2).shape)

(3, 4, 2)
(3, 4)


In [15]:
mean(a, axis=2)

array([[43. , 72.5, 54. , 94. ],
       [22.5, 66.5, 64.5, 31.5],
       [29. , 39. , 57.5, 27. ]])

Ejercicio 7.10.6. Diseñe una función desvtip(a, axis) que haga lo mismo que la función std
utilizando la definición de desviación típica (o estándar):

Haga que axis tenga un valor por defecto None y tenga presente que también puede tomar valores
positivos y negativos. Es recomendable el uso de expand_dims para facilitar el cálculo. Compare
ambas funciones para comprobar que dan los mismos resultados con arrays de prueba de varias
dimensiones.

In [17]:
def desvtip(a, axis): 
    return 