In [1]:
from numpy import *
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
from pprint import pprint

Ejercicio 7.10.5. Diseñe una función media(a, axis) que haga lo mismo que la función mean
utilizando la definición de media: a_m = suma(a[j]) / n

Haga que axis tenga un valor por defecto None y tenga presente que también puede tomar valores
positivos y negativos. Compare ambas funciones para comprobar que dan los mismos resultados con
arrays de prueba de varias dimensiones.

In [115]:
a = random.randint(0, 100, size=(3, 4, 2))

pprint(a)
pprint(a.shape)
s = sum(a, axis=0)
pprint(s)
pprint(s.shape)
n = prod(a.shape) / prod(s.shape)
pprint(n)
pprint(mean(a, axis=0))
pprint(sum(a, axis=0) / n)


array([[[27, 71],
        [14, 45],
        [15, 80],
        [92, 67]],

       [[81, 14],
        [22, 60],
        [72, 33],
        [38, 37]],

       [[33, 38],
        [66, 64],
        [ 8, 66],
        [88, 54]]])
(3, 4, 2)
array([[141, 123],
       [102, 169],
       [ 95, 179],
       [218, 158]])
(4, 2)
3.0
array([[47.        , 41.        ],
       [34.        , 56.33333333],
       [31.66666667, 59.66666667],
       [72.66666667, 52.66666667]])
array([[47.        , 41.        ],
       [34.        , 56.33333333],
       [31.66666667, 59.66666667],
       [72.66666667, 52.66666667]])


In [3]:
def media(a, axis=None):
    s = sum(a, axis=axis)
    n = prod(a.shape) / prod(s.shape)
    return s / n


In [20]:
a = random.randint(0, 100, size=(10,))
pprint(media(a))
pprint(mean(a))


47.1
47.1


In [21]:
a = random.randint(0, 100, size=(3, 4))
pprint(media(a))
pprint(mean(a))

47.416666666666664
47.416666666666664


In [22]:
pprint(media(a, axis=0))
pprint(mean(a, axis=0))

array([48.66666667, 62.33333333, 58.66666667, 20.        ])
array([48.66666667, 62.33333333, 58.66666667, 20.        ])


In [23]:
pprint(media(a, axis=1))
pprint(mean(a, axis=1))

array([65.25, 41.25, 35.75])
array([65.25, 41.25, 35.75])


In [24]:
a = random.randint(0, 100, size=(3, 4, 2))
pprint(media(a))
pprint(mean(a))

48.416666666666664
48.416666666666664


In [26]:
pprint(media(a, axis=(-1, -2)))
pprint(mean(a, axis=(-1, -2)))

array([45.25, 45.25, 54.75])
array([45.25, 45.25, 54.75])


In [11]:
axis = None
pprint(sum(a, axis=axis).shape)
pprint(int(prod(sum(a, axis=axis).shape)))
pprint(int(prod(a.shape)/prod(sum(a, axis=axis).shape)))
pprint(int(prod(a.shape)))

()
1
24
24


In [12]:
axis = 0
pprint(sum(a, axis=axis).shape)
pprint(int(prod(sum(a, axis=axis).shape)))
pprint(int(prod(a.shape)/prod(sum(a, axis=axis).shape)))
pprint(int(prod(a.shape)))

(4, 2)
8
3
24


In [13]:
axis = (0,1)
pprint(sum(a, axis=axis).shape)
pprint(int(prod(sum(a, axis=axis).shape)))
pprint(int(prod(a.shape)/prod(sum(a, axis=axis).shape)))
pprint(int(prod(a.shape)))

(2,)
2
12
24


In [14]:
pprint(a.shape)
pprint(sum(a, axis=2).shape)

(3, 4, 2)
(3, 4)


In [15]:
mean(a, axis=2)

array([[43. , 72.5, 54. , 94. ],
       [22.5, 66.5, 64.5, 31.5],
       [29. , 39. , 57.5, 27. ]])

In [62]:
x = array([1, 2])
pprint(x.shape)

(2,)


In [63]:
expand_dims(x, axis=0).shape

(1, 2)

In [46]:
x.reshape(1, -1)

array([[1, 2]])

In [59]:
x = array([1, 2])
pprint(x.shape)
expand_dims(x, axis=1).shape

(2,)


(2, 1)

In [49]:
x.reshape(-1, 1)

array([[1],
       [2]])

In [52]:
x = array([1, 2])
pprint(x)
expand_dims(x, axis=(1,2))

array([1, 2])


array([[[1]],

       [[2]]])

In [57]:
expand_dims(x, axis=(0,1,3)).shape

(1, 1, 2, 1)

In [114]:
expand_dims(x, axis=(0,1,3)).shape

(1, 1, 2, 1)

Ejercicio 7.10.6. Diseñe una función desvtip(a, axis) que haga lo mismo que la función std
utilizando la definición de desviación típica (o estándar):

desv_tip = sqrt( sum( ( a[j] - a_media)**2 ) / n )

Haga que axis tenga un valor por defecto None y tenga presente que también puede tomar valores
positivos y negativos. Es recomendable el uso de expand_dims para facilitar el cálculo. Compare
ambas funciones para comprobar que dan los mismos resultados con arrays de prueba de varias
dimensiones.

In [98]:
def desvtip(a, axis=None):
    s = sum(a, axis=axis)
    n = prod(a.shape) / prod(s.shape)
    media = s / n
    if axis is not None:
        media = expand_dims(media, axis=axis)
    return sqrt( sum( (a - media )**2 , axis=axis) / n )


In [99]:
a = random.randint(0, 100, size=(10,))
pprint(desvtip(a))
pprint(std(a))


24.859605789312106
24.859605789312106


In [100]:
a = random.randint(0, 100, size=(3, 4))
pprint(desvtip(a))
pprint(std(a))

22.545632737972905
22.545632737972905


In [101]:
pprint(desvtip(a, axis=0))
pprint(std(a, axis=0))

array([10.96458947, 29.16999981, 18.83259586, 10.23067284])
array([10.96458947, 29.16999981, 18.83259586, 10.23067284])


In [102]:
pprint(desvtip(a, axis=1))
pprint(std(a, axis=1))

array([26.96757312, 11.12148821, 24.55987581])
array([26.96757312, 11.12148821, 24.55987581])


In [116]:
a = random.randint(0, 100, size=(3, 4))

In [117]:
print(a)
print(a.shape)

[[76 84 32 90]
 [71 27 45 67]
 [ 3 73 34 78]]
(3, 4)


In [118]:
axis=0
s = sum(a, axis=axis)
print(s)
print(s.shape)

[150 184 111 235]
(4,)


In [121]:
pprint(a.shape)
pprint(s.shape)

n = prod(a.shape) / prod(s.shape)
pprint(n)

(3, 4)
(4,)
3.0


In [123]:
media = s / n
pprint(media)
pprint(media.shape)

array([50.        , 61.33333333, 37.        , 78.33333333])
(4,)


In [126]:
pprint(a.shape)
pprint(media.shape)
pprint(axis)
pprint(expand_dims(media, axis=axis).shape)

(3, 4)
(4,)
0
(1, 4)


In [127]:
if axis is not None:
    media = expand_dims(media, axis=axis)
pprint(media.shape)

(1, 4)


In [131]:
pprint(a)
pprint(media)
pprint(a - media)

(a - media)**2

array([[76, 84, 32, 90],
       [71, 27, 45, 67],
       [ 3, 73, 34, 78]])
array([[50.        , 61.33333333, 37.        , 78.33333333]])
array([[ 26.        ,  22.66666667,  -5.        ,  11.66666667],
       [ 21.        , -34.33333333,   8.        , -11.33333333],
       [-47.        ,  11.66666667,  -3.        ,  -0.33333333]])


array([[6.76000000e+02, 5.13777778e+02, 2.50000000e+01, 1.36111111e+02],
       [4.41000000e+02, 1.17877778e+03, 6.40000000e+01, 1.28444444e+02],
       [2.20900000e+03, 1.36111111e+02, 9.00000000e+00, 1.11111111e-01]])

In [134]:
sum( (a - media )**2 , axis=axis) / n

array([1108.66666667,  609.55555556,   32.66666667,   88.22222222])

In [135]:
sqrt( sum( (a - media )**2 , axis=axis) / n )

array([33.29664648, 24.68917892,  5.71547607,  9.39266854])

In [136]:
print(a)
print(a.shape)

[[76 84 32 90]
 [71 27 45 67]
 [ 3 73 34 78]]
(3, 4)


In [137]:
axis=1
s = sum(a, axis=axis)
print(s)
print(s.shape)

[282 210 188]
(3,)


In [139]:
pprint(a.shape)
pprint(s.shape)

n = prod(a.shape) / prod(s.shape)
pprint(n)

(3, 4)
(3,)
4.0


In [140]:
media = s / n
pprint(media)
pprint(media.shape)

array([70.5, 52.5, 47. ])
(3,)


In [141]:
pprint(a.shape)
pprint(media.shape)
pprint(axis)
pprint(expand_dims(media, axis=axis).shape)

(3, 4)
(3,)
1
(3, 1)


In [142]:
if axis is not None:
    media = expand_dims(media, axis=axis)
pprint(media.shape)

(3, 1)


In [143]:
pprint(a)
pprint(media)
pprint(a - media)

(a - media)**2

array([[76, 84, 32, 90],
       [71, 27, 45, 67],
       [ 3, 73, 34, 78]])
array([[70.5],
       [52.5],
       [47. ]])
array([[  5.5,  13.5, -38.5,  19.5],
       [ 18.5, -25.5,  -7.5,  14.5],
       [-44. ,  26. , -13. ,  31. ]])


array([[  30.25,  182.25, 1482.25,  380.25],
       [ 342.25,  650.25,   56.25,  210.25],
       [1936.  ,  676.  ,  169.  ,  961.  ]])

In [144]:
sum( (a - media )**2 , axis=axis) / n

array([518.75, 314.75, 935.5 ])

In [145]:
sqrt( sum( (a - media )**2 , axis=axis) / n )

array([22.77608395, 17.741195  , 30.58594448])

In [146]:
a = random.randint(0, 100, size=(3, 4, 5, 6))
pprint(desvtip(a))
pprint(std(a))

29.484787744417176
29.484787744417176


In [147]:
pprint(desvtip(a, axis=(1,2,3)))
pprint(std(a, axis=(1,2,3)))

array([29.88488911, 29.35344836, 29.08348973])
array([29.88488911, 29.35344836, 29.08348973])


In [149]:
pprint(desvtip(a, axis=(0, -1, -2)))
pprint(std(a, axis=(0, -1, -2)))

array([28.79201707, 28.61731324, 29.13429103, 30.49045388])
array([28.79201707, 28.61731324, 29.13429103, 30.49045388])


In [150]:
pprint(desvtip(a, axis=(1, 2)))
pprint(std(a, axis=(1, 2)))

array([[30.36033597, 29.11679069, 29.79916106, 27.87628921, 30.13984074,
        30.38959526],
       [28.01231872, 26.6117925 , 29.87118176, 33.88746081, 29.61097769,
        24.27606846],
       [29.53116997, 29.12365877, 25.5450093 , 25.41771036, 30.239833  ,
        29.79865769]])
array([[30.36033597, 29.11679069, 29.79916106, 27.87628921, 30.13984074,
        30.38959526],
       [28.01231872, 26.6117925 , 29.87118176, 33.88746081, 29.61097769,
        24.27606846],
       [29.53116997, 29.12365877, 25.5450093 , 25.41771036, 30.239833  ,
        29.79865769]])
