In [1]:
from numpy import *

In [2]:
ts = arange(0 + 10/50, 10 + 10/50, 10/50)
# ts = linspace(0, 10, 50)

In [3]:
ts

array([ 0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,
        2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,
        4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,
        6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,
        9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [4]:
rs = array([ 0.5, 0.75, 1 ])

In [5]:
R = 1
v = 1
w = 1

In [6]:
w*ts

array([ 0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,
        2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,
        4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,
        6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,
        9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [7]:
rs.reshape([3, 1])*cos(w*ts)/R

array([[ 0.49003329,  0.4605305 ,  0.41266781,  0.34835335,  0.27015115,
         0.18117888,  0.08498357, -0.01459976, -0.11360105, -0.20807342,
        -0.29425056, -0.36869686, -0.42844438, -0.47111117, -0.49499625,
        -0.49914739, -0.4833991 , -0.44837921, -0.39548386, -0.32682181,
        -0.24513041, -0.15366643, -0.05607626,  0.04374949,  0.14183109,
         0.23425834,  0.31734644,  0.38778294,  0.44275976,  0.48008514,
         0.49827105,  0.49659246,  0.4751163 ,  0.43469875,  0.37695113,
         0.30417566,  0.21927366,  0.12562992,  0.02697771, -0.07275002,
        -0.16957743, -0.25964433, -0.33936002, -0.40554651, -0.45556513,
        -0.48742181, -0.49984652, -0.49234393, -0.46521314, -0.41953576],
       [ 0.73504993,  0.69079575,  0.61900171,  0.52253003,  0.40522673,
         0.27176832,  0.12747536, -0.02189964, -0.17040157, -0.31211013,
        -0.44137584, -0.55304529, -0.64266657, -0.70666676, -0.74249437,
        -0.74872108, -0.72509864, -0.67256881, -0.

In [8]:
v*ts

array([ 0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,
        2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,
        4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,
        6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,
        9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [9]:
rs.reshape([3, 1]) / R

array([[0.5 ],
       [0.75],
       [1.  ]])

In [10]:
cos(w*ts)

array([ 0.98006658,  0.92106099,  0.82533561,  0.69670671,  0.54030231,
        0.36235775,  0.16996714, -0.02919952, -0.22720209, -0.41614684,
       -0.58850112, -0.73739372, -0.85688875, -0.94222234, -0.9899925 ,
       -0.99829478, -0.96679819, -0.89675842, -0.79096771, -0.65364362,
       -0.49026082, -0.30733287, -0.11215253,  0.08749898,  0.28366219,
        0.46851667,  0.63469288,  0.77556588,  0.88551952,  0.96017029,
        0.9965421 ,  0.99318492,  0.95023259,  0.86939749,  0.75390225,
        0.60835131,  0.43854733,  0.25125984,  0.05395542, -0.14550003,
       -0.33915486, -0.51928865, -0.67872005, -0.81109301, -0.91113026,
       -0.97484362, -0.99969304, -0.98468786, -0.93042627, -0.83907153])

In [11]:
( rs.reshape([3, 1]) / R ) * cos(w*ts)

array([[ 0.49003329,  0.4605305 ,  0.41266781,  0.34835335,  0.27015115,
         0.18117888,  0.08498357, -0.01459976, -0.11360105, -0.20807342,
        -0.29425056, -0.36869686, -0.42844438, -0.47111117, -0.49499625,
        -0.49914739, -0.4833991 , -0.44837921, -0.39548386, -0.32682181,
        -0.24513041, -0.15366643, -0.05607626,  0.04374949,  0.14183109,
         0.23425834,  0.31734644,  0.38778294,  0.44275976,  0.48008514,
         0.49827105,  0.49659246,  0.4751163 ,  0.43469875,  0.37695113,
         0.30417566,  0.21927366,  0.12562992,  0.02697771, -0.07275002,
        -0.16957743, -0.25964433, -0.33936002, -0.40554651, -0.45556513,
        -0.48742181, -0.49984652, -0.49234393, -0.46521314, -0.41953576],
       [ 0.73504993,  0.69079575,  0.61900171,  0.52253003,  0.40522673,
         0.27176832,  0.12747536, -0.02189964, -0.17040157, -0.31211013,
        -0.44137584, -0.55304529, -0.64266657, -0.70666676, -0.74249437,
        -0.74872108, -0.72509864, -0.67256881, -0.

In [12]:
R = 1
v = 1
w = 1

def f(r, t):
    return array([
        r / R * cos(w * t) + v * t,
        - r / R * sin(w * t),
        v - v * r / R * sin(w * t),
        -v * r / R * cos(w * t)
    ])

In [13]:
f(1, 0)

array([ 1., -0.,  1., -1.])

In [14]:
rs.reshape([3, 1])

array([[0.5 ],
       [0.75],
       [1.  ]])

In [15]:
ts

array([ 0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,
        2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,
        4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,
        6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,
        9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [ ]:
# https://www.scaler.com/topics/build-the-cartesian-product-using-numpy/

In [16]:
rr = rs.reshape([3, 1]) * ones([50])

In [17]:
tt = ts.reshape([1, 50]) * ones([3, 1])

In [32]:
rr, tt = meshgrid(rs, ts)

In [36]:
rr

array([[0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
       [0.5 , 0.75, 1.  ],
 

In [28]:
tt

array([[ 0.2,  0.2,  0.2],
       [ 0.4,  0.4,  0.4],
       [ 0.6,  0.6,  0.6],
       [ 0.8,  0.8,  0.8],
       [ 1. ,  1. ,  1. ],
       [ 1.2,  1.2,  1.2],
       [ 1.4,  1.4,  1.4],
       [ 1.6,  1.6,  1.6],
       [ 1.8,  1.8,  1.8],
       [ 2. ,  2. ,  2. ],
       [ 2.2,  2.2,  2.2],
       [ 2.4,  2.4,  2.4],
       [ 2.6,  2.6,  2.6],
       [ 2.8,  2.8,  2.8],
       [ 3. ,  3. ,  3. ],
       [ 3.2,  3.2,  3.2],
       [ 3.4,  3.4,  3.4],
       [ 3.6,  3.6,  3.6],
       [ 3.8,  3.8,  3.8],
       [ 4. ,  4. ,  4. ],
       [ 4.2,  4.2,  4.2],
       [ 4.4,  4.4,  4.4],
       [ 4.6,  4.6,  4.6],
       [ 4.8,  4.8,  4.8],
       [ 5. ,  5. ,  5. ],
       [ 5.2,  5.2,  5.2],
       [ 5.4,  5.4,  5.4],
       [ 5.6,  5.6,  5.6],
       [ 5.8,  5.8,  5.8],
       [ 6. ,  6. ,  6. ],
       [ 6.2,  6.2,  6.2],
       [ 6.4,  6.4,  6.4],
       [ 6.6,  6.6,  6.6],
       [ 6.8,  6.8,  6.8],
       [ 7. ,  7. ,  7. ],
       [ 7.2,  7.2,  7.2],
       [ 7.4,  7.4,  7.4],
 

In [42]:
# https://stackoverflow.com/questions/20228546/how-do-i-apply-some-function-to-a-python-meshgrid

a = [ 1, 2, 3, 4]

@vectorize
def func(x,y):
    return a[x] + a[y]

X,Y = mgrid[1:3, 1:4]
X = X.T
Y = Y.T

Z = func(X, Y)

In [40]:
X

array([[1, 2],
       [1, 2],
       [1, 2]])

In [41]:
Y


array([[1, 1],
       [2, 2],
       [3, 3]])

In [39]:
Z

array([[4, 5],
       [5, 6],
       [6, 7]])

In [43]:
rr = rs.reshape([3, 1]) * ones([50])
tt = ts.reshape([1, 50]) * ones([3, 1])

In [45]:
tt

array([[ 0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,
         2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,
         4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,
         6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,
         9. ,  9.2,  9.4,  9.6,  9.8, 10. ],
       [ 0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,
         2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,
         4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,
         6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,
         9. ,  9.2,  9.4,  9.6,  9.8, 10. ],
       [ 0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,
         2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,
         4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,
         6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,
         9. ,  9.2,  9

In [54]:
R = 1
v = 1
w = 1

def f(r, t):
    return array([
        r / R * cos(w * t) + v * t,
        - r / R * sin(w * t),
        v - v * r / R * sin(w * t),
        -v * r / R * cos(w * t)
    ])

@vectorize
def ff(r, t, i=0):
    return f(r, t, i)

In [57]:
rr = rs.reshape([3, 1]) * ones([50])
tt = ts.reshape([1, 50]) * ones([3, 1])


f(rr, tt).shape

(4, 3, 50)