In [1]:
from numpy import *

In [2]:
A = array([[1, 2, 3, 4, 5, 6, 7, 8], [8, 7, 6, 5, 4, 3, 2, 1]])

A.shape

(2, 8)

In [3]:
B = ones([1,8])

B.shape

(1, 8)

In [4]:
A+B

array([[2., 3., 4., 5., 6., 7., 8., 9.],
       [9., 8., 7., 6., 5., 4., 3., 2.]])

In [5]:
(A+B).shape

(2, 8)

In [6]:
A + ones([1,1])

array([[2., 3., 4., 5., 6., 7., 8., 9.],
       [9., 8., 7., 6., 5., 4., 3., 2.]])

In [7]:
A + ones([1,8])

array([[2., 3., 4., 5., 6., 7., 8., 9.],
       [9., 8., 7., 6., 5., 4., 3., 2.]])

In [8]:
A + ones([2,1])

array([[2., 3., 4., 5., 6., 7., 8., 9.],
       [9., 8., 7., 6., 5., 4., 3., 2.]])

In [9]:
A + ones([2,8]) # NO

array([[2., 3., 4., 5., 6., 7., 8., 9.],
       [9., 8., 7., 6., 5., 4., 3., 2.]])

In [10]:
A + ones([])

array([[2., 3., 4., 5., 6., 7., 8., 9.],
       [9., 8., 7., 6., 5., 4., 3., 2.]])

In [11]:
A + ones([1])

array([[2., 3., 4., 5., 6., 7., 8., 9.],
       [9., 8., 7., 6., 5., 4., 3., 2.]])

In [12]:
A + ones([8])

array([[2., 3., 4., 5., 6., 7., 8., 9.],
       [9., 8., 7., 6., 5., 4., 3., 2.]])

In [13]:
A + ones([1,1,1])

array([[[2., 3., 4., 5., 6., 7., 8., 9.],
        [9., 8., 7., 6., 5., 4., 3., 2.]]])

In [14]:
A + ones([1,1,1,1])

array([[[[2., 3., 4., 5., 6., 7., 8., 9.],
         [9., 8., 7., 6., 5., 4., 3., 2.]]]])

In [15]:
A + ones([1,1,1,8])

array([[[[2., 3., 4., 5., 6., 7., 8., 9.],
         [9., 8., 7., 6., 5., 4., 3., 2.]]]])

In [16]:
A + ones([1,2,8])

array([[[2., 3., 4., 5., 6., 7., 8., 9.],
        [9., 8., 7., 6., 5., 4., 3., 2.]]])

In [17]:
A + ones([1,1,2,8])

array([[[[2., 3., 4., 5., 6., 7., 8., 9.],
         [9., 8., 7., 6., 5., 4., 3., 2.]]]])

In [18]:
A + ones([1,1,2,1])

array([[[[2., 3., 4., 5., 6., 7., 8., 9.],
         [9., 8., 7., 6., 5., 4., 3., 2.]]]])

In [19]:
C = full([1, 2, 1], 10)

In [20]:
A * C

array([[[10, 20, 30, 40, 50, 60, 70, 80],
        [80, 70, 60, 50, 40, 30, 20, 10]]])

In [21]:
A + ( 10 * ones([1, 1, 1]) )

array([[[11., 12., 13., 14., 15., 16., 17., 18.],
        [18., 17., 16., 15., 14., 13., 12., 11.]]])

In [22]:
A + full([1, 1, 1], 10)

array([[[11, 12, 13, 14, 15, 16, 17, 18],
        [18, 17, 16, 15, 14, 13, 12, 11]]])

In [23]:
A + full([1, 2, 8], 10)

array([[[11, 12, 13, 14, 15, 16, 17, 18],
        [18, 17, 16, 15, 14, 13, 12, 11]]])

In [24]:
A + full([1, 1, 8], 10)

array([[[11, 12, 13, 14, 15, 16, 17, 18],
        [18, 17, 16, 15, 14, 13, 12, 11]]])

In [25]:
A + full([1, 2, 1], 10)

array([[[11, 12, 13, 14, 15, 16, 17, 18],
        [18, 17, 16, 15, 14, 13, 12, 11]]])

In [26]:
A + full([3, 2, 8], 10)

array([[[11, 12, 13, 14, 15, 16, 17, 18],
        [18, 17, 16, 15, 14, 13, 12, 11]],

       [[11, 12, 13, 14, 15, 16, 17, 18],
        [18, 17, 16, 15, 14, 13, 12, 11]],

       [[11, 12, 13, 14, 15, 16, 17, 18],
        [18, 17, 16, 15, 14, 13, 12, 11]]])

In [27]:
A * full([1, 1, 1], 10)

array([[[10, 20, 30, 40, 50, 60, 70, 80],
        [80, 70, 60, 50, 40, 30, 20, 10]]])

In [28]:
A * full([1, 2, 8], 10)

array([[[10, 20, 30, 40, 50, 60, 70, 80],
        [80, 70, 60, 50, 40, 30, 20, 10]]])

In [29]:
A * full([1, 1, 8], 10)

array([[[10, 20, 30, 40, 50, 60, 70, 80],
        [80, 70, 60, 50, 40, 30, 20, 10]]])

In [30]:
A * full([1, 2, 1], 10)

array([[[10, 20, 30, 40, 50, 60, 70, 80],
        [80, 70, 60, 50, 40, 30, 20, 10]]])

In [31]:
A * full([3, 2, 8], 10)

array([[[10, 20, 30, 40, 50, 60, 70, 80],
        [80, 70, 60, 50, 40, 30, 20, 10]],

       [[10, 20, 30, 40, 50, 60, 70, 80],
        [80, 70, 60, 50, 40, 30, 20, 10]],

       [[10, 20, 30, 40, 50, 60, 70, 80],
        [80, 70, 60, 50, 40, 30, 20, 10]]])

In [36]:
A.shape

(2, 8)

In [32]:
C + B

array([[[11., 11., 11., 11., 11., 11., 11., 11.],
        [11., 11., 11., 11., 11., 11., 11., 11.]]])

In [33]:
B.shape

(1, 8)

In [34]:
C.shape

(1, 2, 1)

In [35]:
(B+C).shape

(1, 2, 8)