In [1]:
from numpy import *
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
from pprint import pprint

In [20]:
v = array([ 1,2,3,4,5 ])
pprint(v.shape)
pprint(v)
pprint(v[1])

(5,)
array([1, 2, 3, 4, 5])
2


In [25]:
v1 = v.reshape([5, 1])
pprint(v1.shape)
pprint(v1)
pprint(v1[1,0])

(5, 1)
array([[1],
       [2],
       [3],
       [4],
       [5]])
2


In [27]:
v2 = v.reshape([1, 5])
pprint(v2.shape)
pprint(v2)
pprint(v2[0,1])

(1, 5)
array([[1, 2, 3, 4, 5]])
2


In [28]:
v3 = v.reshape([1, 1, 5, 1, 1])
pprint(v3.shape)
pprint(v3)
pprint(v3[0,0,1,0,0])

(1, 1, 5, 1, 1)
array([[[[[1]],

         [[2]],

         [[3]],

         [[4]],

         [[5]]]]])
2


In [ ]:
# datos[indice_temperatura, indice_tiempo]

In [45]:
# temperatura[indice_temperatura, indice_tiempo] = temperatura[indice_temperatura]
temperatura = array( [60,70,80,90,100] ).reshape(-1, 1)
pprint(temperatura.shape)
pprint(temperatura)
pprint(temperatura[1,0])

(5, 1)
array([[ 60],
       [ 70],
       [ 80],
       [ 90],
       [100]])
70


In [46]:
# tiempo[indice_temperatura, indice_tiempo] = tiempo[indice_tiempo]
tiempo = array( [1,2,3,4] ).reshape(1, -1)
pprint(tiempo.shape)
pprint(tiempo)

(1, 4)
array([[1, 2, 3, 4]])


In [47]:
pprint(temperatura * tiempo)


array([[ 60, 120, 180, 240],
       [ 70, 140, 210, 280],
       [ 80, 160, 240, 320],
       [ 90, 180, 270, 360],
       [100, 200, 300, 400]])


In [50]:
temperatura = array( [60,70,80,90,100] )
pprint(temperatura.shape)
pprint(temperatura)
pprint(temperatura[1])

(5,)
array([ 60,  70,  80,  90, 100])
70


In [52]:
tiempo = array( [1,2,3,4] )
pprint(tiempo.shape)
pprint(tiempo)

(4,)
array([1, 2, 3, 4])


In [60]:
s = temperatura.reshape(-1, 1) * tiempo.reshape(1, -1)
pprint(s.shape)
pprint(s)

(5, 4)
array([[ 60, 120, 180, 240],
       [ 70, 140, 210, 280],
       [ 80, 160, 240, 320],
       [ 90, 180, 270, 360],
       [100, 200, 300, 400]])


In [61]:
h = linspace(0, 10, 6).reshape(1,1,-1)
pprint(h.shape)
pprint(h)

(1, 1, 6)
array([[[ 0.,  2.,  4.,  6.,  8., 10.]]])


In [64]:
s.reshape(5, 4, 1) * h

array([[[   0.,  120.,  240.,  360.,  480.,  600.],
        [   0.,  240.,  480.,  720.,  960., 1200.],
        [   0.,  360.,  720., 1080., 1440., 1800.],
        [   0.,  480.,  960., 1440., 1920., 2400.]],

       [[   0.,  140.,  280.,  420.,  560.,  700.],
        [   0.,  280.,  560.,  840., 1120., 1400.],
        [   0.,  420.,  840., 1260., 1680., 2100.],
        [   0.,  560., 1120., 1680., 2240., 2800.]],

       [[   0.,  160.,  320.,  480.,  640.,  800.],
        [   0.,  320.,  640.,  960., 1280., 1600.],
        [   0.,  480.,  960., 1440., 1920., 2400.],
        [   0.,  640., 1280., 1920., 2560., 3200.]],

       [[   0.,  180.,  360.,  540.,  720.,  900.],
        [   0.,  360.,  720., 1080., 1440., 1800.],
        [   0.,  540., 1080., 1620., 2160., 2700.],
        [   0.,  720., 1440., 2160., 2880., 3600.]],

       [[   0.,  200.,  400.,  600.,  800., 1000.],
        [   0.,  400.,  800., 1200., 1600., 2000.],
        [   0.,  600., 1200., 1800., 2400., 3000.],
    

In [ ]:
# datos[indice_A, indice_B, indice_C, indice_D]

In [58]:
datos_A = linspace(0, 10, 6).reshape(-1,1,1)
pprint(datos_A.shape)
pprint(datos_A)

(6, 1, 1)
array([[[ 0.]],

       [[ 2.]],

       [[ 4.]],

       [[ 6.]],

       [[ 8.]],

       [[10.]]])


In [14]:
a = array([ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ])
pprint(a.shape)
pprint(a)

(4, 3)
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])


In [8]:
pprint(a)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])


In [89]:
# xx = xx[ixx]    ixx = [ 0, 1, 2, 3, 4, 5]
# yy = yy[iyy]    iyy = [ 0, 1, 2, 3 ]

xx = linspace(0, 1, 6)
pprint(xx)
yy = linspace(1, 4, 4)
pprint(yy)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])
array([1., 2., 3., 4.])


In [90]:
X, Y = meshgrid(xx, yy)
pprint(X)
pprint(Y)

array([[0. , 0.2, 0.4, 0.6, 0.8, 1. ],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. ],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. ],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. ]])
array([[1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4.]])


In [91]:
# X = X[iyy, ixx] = xx[ixx]
X[3,5]

1.0

In [92]:
# Y = Y[iyy, ixx] = yy[iyy]
Y[3,5]

4.0

In [75]:
X+Y

array([[1. , 1.2, 1.4, 1.6, 1.8, 2. ],
       [2. , 2.2, 2.4, 2.6, 2.8, 3. ],
       [3. , 3.2, 3.4, 3.6, 3.8, 4. ],
       [4. , 4.2, 4.4, 4.6, 4.8, 5. ]])

In [79]:
xx.reshape(1,-1) + yy.reshape(-1,1)

array([[1. , 1.2, 1.4, 1.6, 1.8, 2. ],
       [2. , 2.2, 2.4, 2.6, 2.8, 3. ],
       [3. , 3.2, 3.4, 3.6, 3.8, 4. ],
       [4. , 4.2, 4.4, 4.6, 4.8, 5. ]])