Se quiere analizar el tiro parab´olico en un terreno plano y sin rozamiento del aire. Las ecuaciones
que lo gobiernan en funci´on del tiempo son:

x = vt cos a, y = vt sin a − 1/2 g t**2,

siendo a el ´angulo de disparo, v el m´odulo de la velocidad inicial, y g la aceleraci´on de la
gravedad en el lugar.

Prepare una funci´on coordenadas que tome como argumentos (en el orden indicado): la velo-
cidad, el ´angulo de disparo, el tiempo y la aceleraci´on de la gravedad (´esta con un valor por
defecto de 9.81 m/s2). La funci´on debe devolver un array de Numpy con los valores x e y en
forma de vector columna. Adem´as debe ser una funci´on universal de numpy. (0.5 puntos)
Prepare tres arrays de numpy (0.3 puntos):

 * velocidad inicial, v, de 50 m/s a 100 m/s en pasos de 10 m/s, sin incluir el extremo
superior.

 * ´angulo de disparo, a, desde 45◦ a 90◦ com pasos de 5◦, sin incluir el extremo superior.

 * 50 tiempos, t, en total igualmente espaciados desde 0 s a 10 s, incluyendo ambos extremos.

Cambie la forma a los arrays anteriormente creados de manera que puedan se usados en la
funci´on coordenadas para que ´esta devuelva un array de Numpy de cuatro dimensiones con
la estructura siguiente: la primera dimensi´on corresponde a los valores de v, la segunda a los
valores de ´angulo a, la tercera a los diferentes tiempos, t. La cuarta dimensi´on contiene las dos
componentes de posici´on, x e y. (0.3 puntos)

Usando la funci´on coordenadas, prepare un array de Numpy de cuatro dimensiones denominado
resul, a partir de los datos anteriormente citados. (0.3 puntos)

Finalmente realice una gr´afica con matplotlib de las trayectorias para cada uno de los valores
de v antes indicados, con su leyenda correspondiente, y etiquetando los ejes. (0.6 puntos)

In [173]:
from numpy import *
import matplotlib as plt

from pprint import pprint

def coordenadas(v, a, t, g=9.81):
    x = v*t*cos(a * pi / 180)
    y = v*t*sin(a * pi / 180) - 0.5*g*t**2
    array1=array([x, y])
    return array1



In [174]:
print(coordenadas(50, 2, 3))

[149.90862405 -38.91007549]


In [175]:
v_inicial = arange(50, 100, 10)
print(v_inicial.shape)

a = arange(45, 90, 5)#grados
print(a.shape)

tiempos=linspace(0,10,50)
print(tiempos.shape)

(5,)
(9,)
(50,)


In [176]:
v_inicial.shape=(5,1,1)
a.shape=(1,9,1)
tiempos.shape=(1,1,50)

print(v_inicial.shape)
print(a.shape)
print(tiempos.shape)

coordenadas(v_inicial, a, tiempos).shape

(5, 1, 1)
(1, 9, 1)
(1, 1, 50)


(2, 5, 9, 50)

In [243]:
v = array(50)
a = array(2)
t = array(3)
g = 9.81

x = v*t*cos(a * pi / 180)
print(x.shape)
y = v*t*sin(a * pi / 180) - 0.5*g*t**2
print(y.shape)
print(stack([x, y], axis=-1))

()
()
[149.90862405 -38.91007549]


In [246]:
v = arange(50, 100, 10).reshape(5,1,1)
a = arange(45, 90, 5).reshape(1,9,1)
t = linspace(0,10,50).reshape(1,1,50)
g = 9.81

x = v*t*cos(a * pi / 180)
print(x.shape)
y = v*t*sin(a * pi / 180) - 0.5*g*t**2
print(y.shape)
print(stack([x, y], axis=-1).shape)

(5, 9, 50)
(5, 9, 50)
(5, 9, 50, 2)


In [241]:
v = arange(50, 100, 10).reshape(5,1,1)
a = arange(45, 90, 5).reshape(1,9,1)
t = linspace(0,10,50).reshape(1,1,50)
g = 9.81

x = v*t*cos(a * pi / 180)
print(x.shape)
y = v*t*sin(a * pi / 180) - 0.5*g*t**2
print(y.shape)
print(array([x, y]).shape)

(5, 9, 50)
(5, 9, 50)
(2, 5, 9, 50)


In [250]:
v = arange(50, 100, 10).reshape(5,1,1)
a = arange(45, 90, 5).reshape(1,9,1)
t = linspace(0,10,50).reshape(1,1,50)

v[:,:,0]

array([[50],
       [60],
       [70],
       [80],
       [90]])

In [251]:
v = array(50)
a = array(2)
t = array(3)
g = 9.81

x = v*t*cos(a * pi / 180)
print(x.shape)
y = v*t*sin(a * pi / 180) - 0.5*g*t**2
print(y.shape)
print(stack([[x, y]], axis=-1))

()
()
[[149.90862405]
 [-38.91007549]]


In [253]:
v = arange(50, 100, 10).reshape(5,1,1)
a = arange(45, 90, 5).reshape(1,9,1)
t = linspace(0,10,50).reshape(1,1,50)
g = 9.81

x = v*t*cos(a * pi / 180)
print(x.shape)
y = v*t*sin(a * pi / 180) - 0.5*g*t**2
print(y.shape)
print(stack([[x, y]], axis=-1).shape)

(5, 9, 50)
(5, 9, 50)
(2, 5, 9, 50, 1)


In [256]:
v = array([50, 52, 54])
a = array([2, 4, 6])
t = array([3, 4, 5])
g = 9.81

x = v*t*cos(a * pi / 180)
print(x.shape)
y = v*t*sin(a * pi / 180) - 0.5*g*t**2
print(y.shape)
print(stack([x, y], axis=-1).T)

(3,)
(3,)
[[149.90862405 207.49332245 268.52091175]
 [-38.91007549 -63.97065346 -94.40231492]]


In [257]:
v = array(50)
a = array(2)
t = array(3)
g = 9.81

x = v*t*cos(a * pi / 180)
print(x.shape)
y = v*t*sin(a * pi / 180) - 0.5*g*t**2
print(y.shape)
print(stack([x, y], axis=-1).T)

()
()
[149.90862405 -38.91007549]


In [259]:
v = arange(50, 100, 10).reshape(5,1,1)
a = arange(45, 90, 5).reshape(1,9,1)
t = linspace(0,10,50).reshape(1,1,50)
g = 9.81

x = v*t*cos(a * pi / 180)
print(x.shape)
y = v*t*sin(a * pi / 180) - 0.5*g*t**2
print(y.shape)
print(stack([x, y], axis=-1).T.shape)

(5, 9, 50)
(5, 9, 50)
(2, 50, 9, 5)


In [263]:
v = array([50])
a = array([2])
t = array([3])
g = 9.81

x = v*t*cos(a * pi / 180)
print(x.shape)
y = v*t*sin(a * pi / 180) - 0.5*g*t**2
print(y.shape)
print(stack([x, y], axis=-1).T)

(1,)
(1,)
[[149.90862405]
 [-38.91007549]]


In [261]:
v = arange(50, 100, 10).reshape(5,1,1)
a = arange(45, 90, 5).reshape(1,9,1)
t = linspace(0,10,50).reshape(1,1,50)
g = 9.81

x = v*t*cos(a * pi / 180)
print(x.shape)
y = v*t*sin(a * pi / 180) - 0.5*g*t**2
print(y.shape)
print(array([x, y]).T.shape)

(5, 9, 50)
(5, 9, 50)
(50, 9, 5, 2)


In [271]:
v = asarray(50).reshape(-1)
a = asarray(2).reshape(-1)
t = asarray(3).reshape(-1)
g = 9.81

x = v*t*cos(a * pi / 180)
print(x.shape)
y = v*t*sin(a * pi / 180) - 0.5*g*t**2
print(y.shape)
print(array([x, y]))

(1,)
(1,)
[[149.90862405]
 [-38.91007549]]


In [272]:
v = arange(50, 100, 10).reshape(5,1,1)
a = arange(45, 90, 5).reshape(1,9,1)
t = linspace(0,10,50).reshape(1,1,50)
g = 9.81

x = v*t*cos(a * pi / 180)
print(x.shape)
y = v*t*sin(a * pi / 180) - 0.5*g*t**2
print(y.shape)
print(column_stack([x, y]).shape)

(5, 9, 50)
(5, 9, 50)
(5, 18, 50)


In [275]:
v = arange(50, 100, 10).reshape(5,1,1,1)
a = arange(45, 90, 5).reshape(1,1,9,1)
t = linspace(0,10,50).reshape(1,1,1,50)
g = 9.81

x = v*t*cos(a * pi / 180)
print(x.shape)
y = v*t*sin(a * pi / 180) - 0.5*g*t**2
print(y.shape)
print(stack([x, y]).shape, axis=-1)

(5, 1, 9, 50)
(5, 1, 9, 50)


TypeError: 'axis' is an invalid keyword argument for print()